Repository AY2425S2-CS2113-T11b-4/tp, pull requests merged in 2025-03, with the labels that each got.

#37 Make dateTime in Appointment class LocalDateTime type. Added JUnit Test Cases.
  src/main/java/ClinicEase.java
  src/main/java/manager/Appointment.java
  src/main/java/manager/ManagementSystem.java
  src/main/java/miscellaneous/Parser.java
  src/main/java/miscellaneous/Ui.java
  src/main/java/storage/patient_data.txt
  src/test/java/manager/ManagementSystemTest.java
  src/test/java/miscellaneous/ParserTest.java
Labels: type.Enhancement

#41 Yukuan edit patients detail
  src/main/java/command/EditPatientCommand.java
  src/main/java/command/EditPatientHistoryCommand.java
  src/main/java/manager/ManagementSystem.java
  src/main/java/manager/Patient.java
  src/main/java/miscellaneous/Parser.java
  src/main/java/miscellaneous/Ui.java
Labels: priority.High

#45 Refine sort-appointment and Added JUnit Test Cases
  src/main/java/command/SortAppointmentCommand.java
  src/main/java/manager/ManagementSystem.java
  src/main/java/miscellaneous/Parser.java
  src/main/java/miscellaneous/Ui.java
  src/test/java/command/AddAppointmentCommandTest.java
  src/test/java/command/DeleteAppointmentCommandTest.java
  src/test/java/command/ListAppointmentCommandTest.java
  src/test/java/command/SortAppointmentCommandTest.java
  src/test/java/manager/ManagementSystemTest.java
  src/test/java/miscellaneous/ParserTest.java
Labels: type.Enhancement, priority.Medium

#47 Linked Patient Class and Appointment Class
  src/main/java/ClinicEase.java
  src/main/java/command/AddAppointmentCommand.java
  src/main/java/manager/Appointment.java
  src/main/java/manager/ManagementSystem.java
  src/main/java/manager/Patient.java
  src/main/java/miscellaneous/Parser.java
  src/main/java/miscellaneous/Ui.java
  src/test/java/command/AddAppointmentCommandTest.java
  src/test/java/command/DeleteAppointmentCommandTest.java
  src/test/java/command/ListAppointmentCommandTest.java
  src/test/java/command/SortAppointmentCommandTest.java
  src/test/java/manager/ManagementSystemTest.java
  src/test/java/miscellaneous/ParserTest.java
Labels: type.Task, priority.Medium

#49 Updated DG and UG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  src/main/java/miscellaneous/Parser.java
Labels: type.Task
